### ISSUE TITLE
copy error after pull message well for quite a long time

### ISSUE THREAD

**Issue by zhyueh** [pipelinedb/pipeline_kafka#32] opened 2016-09-20 07:50 UTC
pipeline kafka report an error 'ERROR : column "" of "stream k_stream" does not exists'.
it happen after I have pull message into pipeline db very well for a few days.
btw there is no "" column in k_stream at all, and the steam k_stream do not modify during these days.
when I got the error report, it would run without any problem after execute consume_end and   consume_begin,  how does this happen?

after I read the code of pipeline kafka, I guest the attlist in copy statement has been modified in running time,

**Comment by derekjn** [comment] 2016-09-20 16:25
Hi @zhyueh,

Just to clarify, no new columns were added to `stream_k` via `ALTER STREAM` during Kafka consumption?

**Comment by zhyueh** [comment] 2016-09-21 02:30
Hi @derekjn 
There is no new columns were added to stream. 
I found that one of my specify scripts executing drop other tables (not including this stream ) just right before this error happen. And I hope this may have a little help.

**Comment by derekjn** [comment] 2016-09-23 03:30
@zhyueh can you provide us with any SQL, such as your stream definitions and the scripts that drop other tables, to help reproduce this issue?

**Comment by zhyueh** [comment] 2016-09-23 15:13
@derekjn 
yes, i have drop u an email attached scripts.

**Comment by derekjn** [comment] 2016-12-04 18:40
This has come up again, and I believe it may be due to not copying the column name string here:

https://github.com/pipelinedb/pipeline_kafka/blob/master/pipeline_kafka.c#L827

I'm guessing that memory gets clobbered at some point, thus the strange column doesn't exist errors.

**Comment by derekjn** [comment] 2016-12-05 02:10
@zhyueh this should be fixed on `master` now, but please let me know if you see the error come up again. Apologies for taking a while on this one, it was extremely difficult to reproduce!

**Closed as completed** 2016-12-25 23:54 UTC
Labels: bug
